name: Copy Image to GHCR
on:
  workflow_dispatch: # Позволяет запускать процесс вручную кнопкой Run workflow

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Disk Space
        run: |
          # Очистка места на диске виртуальной машины GitHub
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo docker image prune -a -f

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          # Используем ваш секрет с именем 1234
          password: ${{ secrets.1234 }} 

      - name: Pull and Push
        run: |
          # Скачиваем оригинальный образ
          docker pull dtunikov/mlnode-api:0.0.3
          
          # Переименовываем его для вашего профиля
          docker tag dtunikov/mlnode-api:0.0.3 ghcr.io/${{ github.repository_owner }}/mlnode-api:0.0.3
          
          # Загружаем в ваш реестр GitHub Packages
          docker push ghcr.io/${{ github.repository_owner }}/mlnode-api:0.0.3
