name: Copy Image
on:
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest
    permissions: # Даем права на запись пакетов прямо здесь
      packages: write
      contents: read
    steps:
      - name: Maximize Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo docker image prune -a -f

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Это стандартный ключ, его НЕ НАДО создавать в настройках

      - name: Pull and Push
        run: |
          docker pull dtunikov/mlnode-api:0.0.3
          docker tag dtunikov/mlnode-api:0.0.3 ghcr.io/${{ github.repository_owner }}/mlnode-api:0.0.3
          docker push ghcr.io/${{ github.repository_owner }}/mlnode-api:0.0.3
